### ISSUE TITLE
Configuring Action Bars Bug

### ISSUE THREAD

**Issue by keltharprime** [brittyazel/Neuron#12]
I've had a problem in Ion for a while.  It's still there in Neuron, hope you can help.

The problem exhibits itself when an action bar disappears, or appears with less buttons than it should have.  If I open config and try to adjust the number of buttons, it won't increase the #, but is will decease and go negative.  At that point, sometimes I can increase it back to the original #, sometimes not.  The problem will persist if I delete the bar and re-add it.

I've never been able to get a response, or any aknowledge ment of this issue from anyone, I've had it since I started playing again when WoD was released.

After switching to Neuron, I do get a debug message.

DEBUG: Bad Global Save Data for NeuronActionBar9 ?
DEBUG: Bad Character Save Data for NeuronActionBar9 ?

I get that everytime I click to increase or decrease the number of buttons on the affected bar.

**Comment by brittyazel** [comment]
Interesting. I'll have to look into this one. Is this on all of your profiles or just on a specific character/profile. I've never seen this issue, so I'm trying to figure out if it's something corrupted in your saved variables or if there's something wrong in the code

**Comment by keltharprime** [comment]
It's on all 3 accounts, and several characters.  Seems more prevalent on 
Paladins, dunno why, but not limited to them.

I've been using this addon from Trinity, through Macaroon, and Ion.  
Some of the data may be that old.  I thought about starting fresh, but 
that's a lot, a lot, of work on 30+ toons.

Thanks.

------ Original Message ------

**Comment by brittyazel** [comment]
I'll do some digging to see if I can track it down, but I'm just warning you that since I have yet to encounter this problem and I haven't heard from anyone else about having this issue, it might just be old, incompatible settings sticking around over years. Unless I can re-create this issue it's going to be SUPER hard to debug

**Comment by keltharprime** [comment]
I hear you, and everyone would like you to work on more useful stuff.  
That said, if you are curious, and if I can send you any files to help, 
let me know.

It started after a couple years of not playing WoW.  It could well be 
that some skipped update was supposed to convert something in the file.  
Thinking more about it, Action Bars 1-8 don't appear to be affected.

Cheers!

Rick

------ Original Message ------

**Comment by brittyazel** [comment]
I still can't replicate this issue. As much as you're going to hate me saying this, I think the problem is a corrupted set of configs. :-/ The only real solution I can think of is to remake your action bar profiles. The good news is that you only really need to create 1 "default" profile and you can use it on any toon you like for the most part, so it's not like starting from scratch for each

**Comment by keltharprime** [comment]
Ok, thx.

What specific files do I need to delete to start "fresh".

Thx.

------ Original Message ------

**Comment by brittyazel** [comment]
you can delete any Neuron related saved variables in your WTF folder which is a SUPER hard reset. Or, the easier way is just to go into Interface>Addons>Neuron>Profiles and hit "Reset Profile". This should purge everything and get you back to normal
