### ISSUE TITLE
After Login I see all bars unhidden

### ISSUE THREAD

**Issue by 40P3** [brittyazel/Neuron#142]
When I log in with the toons, I see the bars visible, even though I set them to be hidden. Bags, Mini option bar, Castbar, secondary main bar and the fourth 4 forgot the name for it.
Every time I log in I have to re-hide them.

**Comment by jomo666** [comment]
Yes, can confirm this issue, after set to hide everything but Action Bar 1, after the `/reload` or relog the:

- Menu bar
- Bag bar
- Status bar 3 (experience bar)
- Status bar 4 (reputation bar)

are again visible.

Ps: what is the benefit naming the bars as "status bar N" instead of the easily rememberable names as "xp-bar, "reputation bar", "cast bar", "fatique bars") etc. ?

**Comment by AlexFolland** [comment]
Yes, it looks like the hidden state isn't maintained between sessions currently.  I've completely deleted these bars from my profile, but it would be useful to be able to hide bars properly.

**Comment by brittyazel** [comment]
@jomo666 there's isn't a benefit. You can name them whatever you like. The defaults when they're created are done so in a loop, so they just inherit generic naming. I could make specific names for the default bars, but I haven't done so yet. Feel free to rename them

**Comment by brittyazel** [comment]
Is this still happening?

**Comment by AlexFolland** [comment]
It was when I last checked 5 months ago.  Please try setting a bar to hidden (middle-click the bar in bar edit mode) and reloading UI.  The hidden bar should stay hidden.

**Comment by 40P3** [comment]
Yes I didn't check options for a while, all looks nice and neat, I mean the text helps a lot what is what.
Thank you so much! 👍

**Comment by 40P3** [comment]
And no hiding issue btw either!
