### ISSUE TITLE
Fishing action button

### ISSUE THREAD

**Issue by Addonman** [brittyazel/Neuron#155]
Is Neuron touching fishing action button?I get it when you fish for drowned mana and you get mark of aqua.....(something) to summon miniboss,but i cant find a way to move.Not sure if its Neuron button or mFB button or soem other button so i am chaseing ususal suspects.

**Comment by brittyazel** [comment]
What is a fish action button lol?

**Comment by jpmeyers** [comment]
I there isn't a UI action button for that.  The "Mark of Aquaos" is an item
that appears in your bags when you fish it up out of Conjurer Margoss'
pond.  Toss it back in to summon the elemental.

**Comment by Addonman** [comment]
I know what it does,but it is random place on my screen and i cant move it. Moveanything  calls it fishing action button and looks like zone or extra action button . Its even had my keybind on it -keybind i remeber doing for extra action button  with betterextraactionbutton ( i dont use that addon any more) addon when Ion or Macaroon didnt handle extra action button well .
FB has something like action button in options but no option to move so it might be his as well but not sure.I asked about it on wowinterface FB addon page as well ,but no answer as of yet.

**Comment by Addonman** [comment]
Just noticed someone posting a bug on FB wowinterface forums about it
"2x [ADDON_ACTION_BLOCKED] AddOn 'FishingBuddy' tried to call the protected function 'FishingActionButton:Hide()'."
which seems game calls it like that as well.

**Comment by brittyazel** [comment]
Strange, I'll have to look into it when I get a chance. This is the first I've ever heard of the fishing action button, but I don't really fish so there's that heh

**Comment by raysmith59** [comment]
There are add-ons that add functionality to the existing ExtraAction (or ZoneAction?) buttons, one that I started using recently is ExtraQuestButton which (with default UI) overrides the EAB when you're in the zone for a quest that has quest item, until a couple of days ago it played well with Neuron (ie. it was a 3rd button that I could place logically) but as of the past couple of days I'm no longer able to move it due to another add-on controlling the button (I'd assume Neuron but it isn't specific).  You may be dealing with something similar from FishingBuddy if it does something similar.  Frankly, I have no idea what changed that may have impacted this functionality, my best guess is that it's a change that came during the hotfix earlier in the week, I don't think the change was add-on specific.

**Comment by brittyazel** [comment]
Closing this because it doesn't seem to be anything I can do to help
