### ISSUE TITLE
New Error - Occurred When Going Out of Combat

### ISSUE THREAD

**Issue by HolteUnderscore** [brittyazel/Neuron#183]
Message: [ADDON_ACTION_BLOCKED] AddOn 'Neuron' tried to call the protected function 'MainMenuBar:ClearAllPoints()'.
Time: Mon Oct 15 10:45:29 2018
Count: 1
Stack: [ADDON_ACTION_BLOCKED] AddOn 'Neuron' tried to call the protected function 'MainMenuBar:ClearAllPoints()'.
Interface\FrameXML\MainMenuBar.lua:43: in function `SetPositionForStatusBars'
Interface\FrameXML\MainMenuBar.lua:8: in function `OnStatusBarsUpdated'
Interface\FrameXML\StatusTrackingManager.lua:179: in function `LayoutBars'
Interface\FrameXML\StatusTrackingManager.lua:84: in function `UpdateBarsShown'
Interface\FrameXML\StatusTrackingManager.lua:206: in function <Interface\FrameXML\StatusTrackingManager.lua:202>

Locals: <none>

**Comment by brittyazel** [comment]
Thanks for this. This is another taint warning. I'll take care of this :-)

**Comment by HolteUnderscore** [comment]
And another one

Message: [ADDON_ACTION_BLOCKED] AddOn 'Neuron' tried to call the protected function 'MainMenuBar:SetPoint()'.
Time: Mon Oct 22 13:08:09 2018
Count: 1
Stack: [ADDON_ACTION_BLOCKED] AddOn 'Neuron' tried to call the protected function 'MainMenuBar:SetPoint()'.
Interface\FrameXML\UIParent.lua:2946: in function `UIParentManageFramePositions'
Interface\FrameXML\UIParent.lua:2329: in function <Interface\FrameXML\UIParent.lua:2316>
[C]: in function `SetAttribute'
Interface\FrameXML\UIParent.lua:3118: in function <Interface\FrameXML\UIParent.lua:3116>
[C]: in function `UIParent_ManageFramePositions'
...ns\Blizzard_TalkingHeadUI\Blizzard_TalkingHeadUI.lua:16: in function <...ns\Blizzard_TalkingHeadUI\Blizzard_TalkingHeadUI.lua:15>
[C]: in function `Show'
...ns\Blizzard_TalkingHeadUI\Blizzard_TalkingHeadUI.lua:155: in function <...ns\Blizzard_TalkingHeadUI\Blizzard_TalkingHeadUI.lua:121>
[C]: in function `TalkingHeadFrame_PlayCurrent'
...ns\Blizzard_TalkingHeadUI\Blizzard_TalkingHeadUI.lua:25: in function <...ns\Blizzard_TalkingHeadUI\Blizzard_TalkingHeadUI.lua:23>

Locals: <none>

**Comment by HolteUnderscore** [comment]
And another when dropping combat on prot paladin

Message: [ADDON_ACTION_BLOCKED] AddOn 'Neuron' tried to call the protected function 'ActionButton2:Hide()'.
Time: Mon Oct 22 16:06:39 2018
Count: 1
Stack: [ADDON_ACTION_BLOCKED] AddOn 'Neuron' tried to call the protected function 'ActionButton2:Hide()'.
Interface\FrameXML\ActionButton.lua:379: in function `ActionButton_Update'
Interface\FrameXML\ActionButton.lua:334: in function `ActionButton_UpdateAction'
Interface\FrameXML\ActionBarController.lua:151: in function `ActionBarController_ResetToDefault'
Interface\FrameXML\ActionBarController.lua:140: in function `ActionBarController_UpdateAll'
Interface\FrameXML\ActionBarController.lua:62: in function <Interface\FrameXML\ActionBarController.lua:51>
[C]: in function `ChangeActionBarPage'
[string "ACTIONPAGE2"]:1: in function <[string "ACTIONPAGE2"]:1>

Locals: <none>

**Comment by brittyazel** [comment]
Yeah I think most of the ActionButton ones are a part of the same root cause. I need to find it though. It's not as easy as just searching for "ActionButton2" as both the object and the command are generated on the fly. I can't put my finger on where the calls are, but I'm almost 100% certain the cause is trying to show or hide these bars while in combat. A better solution is to change the alpha from 0 to 1, as that is not a combat-blockable action. When I get back from Atlanta I'll finish fixing a couple of the bugs I've been working on, push a new build out with the last 2 months of fixes, and try to nail this one down once and for all

**Comment by HolteUnderscore** [comment]
Thanks :)  Truth be told, I'd be happy at the moment with the keybind for the extra action button being persistent, I can live with the others - gets tiresome having to re-set it on every char login.

**Comment by Addonman** [comment]
Its not only one button .I am getting this kind of errors constantly when playing.If you press button during combat most likely you will get this kind of error.And usually bug cathcer warn you about 1 so you can live with it.

**Comment by brittyazel** [comment]
Yes, they are all stemming from the same process. Sometimes it's an action bar, sometimes it's a override button, but the effect is always the same. Hence why I suspect it is coming from the same source, though I can't find what is causing it, and believe me I've spent a TON of time looking. However, since it is harmless to functionality and doesn't report an error outside of bug catcher (taint warnings are different than LUA errors), I have to prioritize game breaking things first
