### ISSUE TITLE
Shaman's Primal Elementalist

### ISSUE THREAD

**Issue by Dasaneux** [brittyazel/Neuron#217]
When using the Elemental Shaman talent 'Primal Elementalist', the pet bar is not showing. I brought this issue up a while ago, and know that you've been busy :)

Being able to use the pet bar when taking this talent is important to ele Shaman.

Anyways, just wanted to remind you :P

**Comment by brittyazel** [comment]
What level do you unlock that takent? I probably need to level a shaman there to test it

**Comment by Dasaneux** [comment]
It's unlocked at level 90. The talent gives you direct control over your elemental's abilities, which you don't have with the untalented elemental summons.

**Comment by brittyazel** [comment]
Well damn. If it helps, you can now drag pet spells to your action bar. Maybe that can hold you over until I can level a shaman to 90.

**Comment by teh-fixerer** [comment]
Apologies if I am interrupting.  

Multiple-alt Neuron user here, but I have a shaman that is level 110.  I hadn't tested recent neuron on him previously, especially elemental since I ran enhance/resto, haven't really worked on him since Legion.

I logged in today (12-20-2018) and had to set my talents from BFA Reset.  Got the "welcome to neuron" message on him too, which had the default action bars.

Picked only the primal elementalist talent, and dropped the 2 elemental spells on my bar.  Cast fire elemental.  For me the default pet bar appeared as expected, with several pet spells in the button area.  Same thing when I cast earth elemental.  Bar faded away when pet de-spawned. In edit mode I could move the pet bar around as usual.

Weird thing is on this one is that blizzard doesn't put most if the spells in the spell book of the elemental when it is talented.  Would be nice if they had something similar to hunter (my main's class) - but it isn't implemented.  I guess that means in this case you wouldn't be able to drag spells onto the main action bar, or re-order the spells on the pet bar, however maybe you could use pet cast macros.

May I suggest deleting your current pet bar and re-adding it from the bar menu.  When I did this, I got a various lua errors, but re-loading UI seemed to fix it.  As a resort, backing up your Addon and WTF files and starting with a fresh neuron setup.  I could maybe provide additional feedback if I know how to help. 

Also pasted a few screenshots of my elementals and pet bars.
![earth elemental](https://user-images.githubusercontent.com/8992077/50284554-f6f08a80-041e-11e9-9cbb-cbb75385e285.jpg)
![fire elemental](https://user-images.githubusercontent.com/8992077/50284565-02dc4c80-041f-11e9-943e-750635d495e2.jpg)

**Comment by Dasaneux** [comment]
Well, I deleted the pet bar, and created a new one … and it works now :P 

I tried for ages to get a working pet bar, and I've no idea what changed, but all's good now.

Thanks teh-fixerer, and yep, I use Neuron on all my toons. With all sorts of macros and bar states.

I'm really looking forward to the new Neuron, to see what it can do :)

**Comment by brittyazel** [comment]
Haha it makes me feel silly that it was such an easy solution this whole time lol. I guess I fixed it at one point (accidentally?), but the solution didn't carry over to the current bar. It makes sense though, in the past month I've effectively rewritten the addon to actually be up to snuff, and it looks like part of that was fixing a lot of these old bugs implicitly.
