### ISSUE TITLE
Neuron 1.0.0 & 1.0.1 fail to load

### ISSUE THREAD

**Issue by alcoho** [brittyazel/Neuron#225]
Hi.

Can you help with...

Message: Interface\AddOns\Neuron\Utilities/DB-Fixer.lua:136: bad argument #1 to 'ipairs' (table expected, got nil)
Time: Tue Dec 25 21:10:53 2018
Count: 1
Stack: Interface\AddOns\Neuron\Utilities/DB-Fixer.lua:136: bad argument #1 to 'ipairs' (table expected, got nil)
[C]: in function `ipairs'
Interface\AddOns\Neuron\Utilities/DB-Fixer.lua:136: in function `DBFixer'
Interface\AddOns\Neuron\Neuron.lua:167: in function <Interface\AddOns\Neuron\Neuron.lua:142>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[1]"]:9: in function <[string "safecall Dispatcher[1]"]:5>
(tail call): ?
...ace\AddOns\Neuron\Libs\AceAddon-3.0\AceAddon-3.0.lua:529: in function `InitializeAddon'
...ace\AddOns\Neuron\Libs\AceAddon-3.0\AceAddon-3.0.lua:644: in function <...ace\AddOns\Neuron\Libs\AceAddon-3.0\AceAddon-3.0.lua:636>

Locals: <none>

loading wow without any other addons, neuron shows no bars, no map button and no response to any /neuron commands including /neuron config.

Thank you

**Comment by brittyazel** [comment]
Unfortunately this means there was in issue with your saved profile, and the migration to the new system used in 1.0 failed. That's why nothing is loaded and there's no minimap icon etc.

Sadly if the migration script didn't execute, it means that you won't be able to carry over your profile to 1.0+. The solution here is to rraet your profile and start fresh or to stay on the 0.9.x build for the time being unitl you have the time to rebuild your bars. Sorry for the less than good news :-\

**Comment by alcoho** [comment]
Thank you for the quick response and thank you for all the work that you
have put into Neuron. Sorting through someone else's spaghetti is arduous
and frustrating and I hope it was satisfying to get it to this stage where
you can rightfully claim it as your own. It is the  best bar mod bar none.
