### ISSUE TITLE
Dragging a mount to a new action bar doesn't work

### ISSUE THREAD

**Issue by raysmith59** [brittyazel/Neuron#244]
Originally the button was blank and didn't do anything, after a reload it shows a ? and still doesn't do anything.  Here's the bar edit/macro text for reference, that seems to be correctish (I tried it without the ; as well, no change):

/cast Chauffeured Mekgineer's Chopper;

(I only have access to that mount on my test toon)

Dragging an ability to the bar worked fine, though.

**Comment by raysmith59** [comment]
Seems like just the one mount, tried half a dozen others including a couple with apostrophes and they were fine but the Chopper doesn't work.

**Comment by brittyazel** [comment]
Odd... sadly I don't have the Chopper to test lol

**Comment by brittyazel** [comment]
Can you make a normal macro in the Blizzard built in macro interface for the Chopper? I'm wondering if it is a game bug

**Comment by teh-fixerer** [comment]
Hopefully no one minds, I did a bit of experimenting here without neuron active, (on alliance).  It does indeed look like a game bug, since if you drag the chopper on a standard blizzard action button, the tool tip became "Summon Chauffeur".  That gave me the inspiration to edit a neuron button to "/cast Summon Chauffeur", and tested as a workaround for now  and the icon displays as you would expect.  I will submit a bug to blizzard after I do a bit of research into whether it already exists as a known bug or has been reported.  Horde does naming things  a bit different and seems to work with dragging as usual.

**Comment by brittyazel** [comment]
Interesting ... Well mystery solved. I'm going to close this ticket because it seems to be out of Neuron's hands to fix it. Thanks for looking into it :-)

**Comment by raysmith59** [comment]
Confirmed, I put in a bug report with Blizzard that will be ignored along with all the rest.  Sigh.
