### ISSUE TITLE
French translation

### ISSUE THREAD

**Issue by SirLagardere** [brittyazel/Neuron#25]
Hi, you'll find joined the french translation.
I think I cover up pretty much everything (except L.INSTALL_MESSAGE and L.UPDATE_WARNING I don't know if you wish to translate these strings).
It's base on the latest relase (0.9.10) from the enUS file.
[Neuron_X-frFR.zip](https://github.com/brittyazel/Neuron/files/1595372/Neuron_X-frFR.zip)

**Comment by brittyazel** [comment]
You Rock!

I'm actually fully redoing the entire localization infrastructure as I type this, and I'm making it so that future strings can be translated directly within Curseforge. I have to completely manually change each and every string though throughout the whole addon to make this work though, so it's going to take a couple hours. I'll make sure to import your strings once I get the infrastructure reworked

Hopefully when I'm done, that will be the end of the bugs related to locales. ;-)

**Comment by brittyazel** [comment]
So I'm modifying the strings quite a bit it turns out. Some of your work won't directly translate across, but most will. Sorry to make you had to redo some, but doing it through curseforge should make it tons easier!

**Comment by SirLagardere** [comment]
No problem on my side. I'll try to keep it up asap on Curseforge :)
On curse, my account is "Cinedelle", just to inform you.
Thanks again for your commitment to this great addon 👍

**Comment by brittyazel** [comment]
Happy Near Year to you as well!

BTW, I have finished implementing the CurseForge translation system:
https://wow.curseforge.com/projects/neuron/localization

Have at it! This way you don't need to wait for me to get the French translations going. It's in your hands :-)

Let me know if you need permissions or something

**Comment by SirLagardere** [comment]
Seems good on Curse. Starting to commit my translation ;)

**Comment by brittyazel** [comment]
Nice work ok the translations! The latest version should have included most of your translations, minus the few that snuck in after I released 0.9.11d.

Do you mind double checking in-game to make sure all your changes look good? I don't have any way of checking this, so I'm going to leave it up to you to tweak the French translations

**Comment by SirLagardere** [comment]
Yep, I'll check and adapt the french strings to get a clean look in the UI ;)

**Comment by brittyazel** [comment]
Haha I haven't used the "translation file" no. I had already changed the enUS file so much I couldn't cleanly copy over the strings.

The way that the translations works (that you've probably seen) is that curseforge automatically pulls in all of the strings when I push a new version. In reality, the only thing I have in the frFR file is:
`--@localization(locale="frFR", format="lua_additive_table")@`
Which get's replaced at build time with the actual strings.

If you want to test your string changes to see how they look in-between my builds, you can use curseforge's export tool and then paste that into your local frFR localization file until you are happy with how it looks :-)

Also, since the new translation strings only go live when a new version is pushed, if you have some pressing Translation fixes that you'd like to see go live, just ask me to push a new build and I will.

**Comment by brittyazel** [comment]
Also, my Bnet tag is Britt#1621 and my Discord is Britt#3502
Feel free to add me if you want to run anything by me (or to actually, you know, play the game lol)

**Comment by brittyazel** [comment]
Closing this for now as you have the translations covered
