### ISSUE TITLE
Talented abilities with stacks not showing correct cooldown indicator

### ISSUE THREAD

**Issue by dpwrussell** [brittyazel/Neuron#266]
One more stack-CD problem I'm afraid. Similar to #239

You can see that Blessed Hammer (between judgement and consecration) has 0 stacks, but it showing as available.

![wowscrnshot_012119_085124](https://user-images.githubusercontent.com/1889043/51493664-f2b4e580-1dad-11e9-815f-d2cf19fcd69a.jpg)

Modified (by talents) abilities are incorrectly displayed. Blessed Hammer replaces Hammer of the Righteous. If I make a new macro for Blessed Hammer specifically it works perfectly, but the HotR macro shows the incorrect availability. There are quite a lot of abilities like this in the game, so probably worth fixing.

I checked what happens with default action bars and a regular blizzard macro. It worked as expected that the HotR button displayed the correct availability when using the Blessed Hammer talent.

**Comment by brittyazel** [comment]
This is a complicated issue. Imagine two abilities, Roll and its upgraded form Chi Torpido. If I query GetSpellInfo("Roll") it will give me correct and accurate info regardless of if we are tallented into Chi Torpedo. However, if I query GetSpellInfo("Chi Torpedo") it will only give me the correct info for Chi Torpedo.

So the issue is this, if I write a macro as "/cast roll", it will always work, as it always gets accurate info from the above function regardless of how we're talented. Though if it's written explicitly as "/cast Chi Torpedo" it will fail to report accurate info unless we are specced into it.

I don't know how to deal with this, as when we write a macro we always write it for the current spell, not the base spell, because we can't query if there even is a base spell. This is a weird side effect of making all spells as macros. Somehow we need to adjust the macro autowrite code to somehow write the macro for the basename, not for the talented name. And this is what I'm not sure how to do

**Comment by brittyazel** [comment]
I'm not sure if this is actually fixed, can you please test the code in MASTER for me? I don't want to push a new release in case there are bugs. Note, only newly dragged abilities will reflect the fix, so you'll have to re-drag Blessed Hammer to your bar.

In essence, this patch does two things, it keeps track of the base (alt) spell name if there is one, and when autowriting a macro checks if there is an alt name, and if that alt name is known (in the case of a base spell), and then uses the alt name for the macro instead. This should work within the confines of the game as it is today
