### ISSUE TITLE
Confused about this addon.

### ISSUE THREAD

**Issue by Nikslg** [brittyazel/Neuron#269]
I am sorry that I am writing it here, but I though that I would drop some suggestions among with questions.

So, my first issue that there no basic interface for it. Pseudo-Blizzard Interface would be nice as hint to what and how to use it. Because there no such thing, new players (me included) might find this addon quite difficult to understand even though this addon has some nice things.
Second issue is that for some reasons, casting bar is missing for me, at all. even after I placed all "default" ones, No casting indications what so ever. Perhaps a bug or am I missing something?
3rd is more of suggestion, for bag panel. Perhaps it would make more sense to keep the large bag instead of small ones would be better? because in 1 button mode the panel becomes unmovable as dragging will move the bag itself.
I really want to understand this addon since I use macro alot. But for now, it's quite difficult to understand what is wrong. It might also be due to Russian client.

**Comment by brittyazel** [comment]
I'm confused about a few points.

1) There's no basic interface for it? When you first log in you should be greeted with something looking very similar to the blizzard stock UI.
![wowscrnshot_020219_104515](https://user-images.githubusercontent.com/3747347/52167935-e1d27100-26d7-11e9-97d8-2a8d6744f46d.jpg)

2) It's odd that the cast bar is missing. This should not be the case unless it was deleted manually. In order to make a new one, first open the bar editor window (left click the minimap icon and then right click on any bar), next click "create new" (or something like that) and then chose status bar, move the status bar to wherever you would like it to go, finally close the bar edit mode and open the button edit mode (right click the minimap icon), and then right click on the specific cast bar button you made, in the button editor window choose "cast bar" as the button type, and make sure the other options all suite your likings.

3)I don't really understand your suggestion here with the bag bar. You don't like that it has all 5 buttons? Also, to move the bag bar you need to first be in bar edit mode. If you only want on button you can always remove the 4 bag buttons that you don't want.

**Comment by Nikslg** [comment]
When I started the addon first time, I had nothing but system buttons in the bottom right part of the screen. This is why I was confused. Cast bar is missing, indeed.
And I am unable to move "specific" bag inside of the bag bar, as I said if I make it show only 1 bag, it shows only small bag, not the big one.
![image](https://user-images.githubusercontent.com/15956980/52168880-cd768e80-2740-11e9-9879-c1226f3a105d.png)

**Comment by Nikslg** [comment]
Bugsack says no errors. But I suppose it is due to Russian locale.
Is it possible for "Light" version just for adding new buttons to work with other interfaces?

**Comment by brittyazel** [comment]
A "Light" version would just be removing all the default bars and buttons. Though I'm not sure what that would do for things like castbars, as we have to disable a number of blizzard default elements to make them work. 

Did you try resetting the profile? If you didn't get the layout that you see above in my screenshot then it's definitely a bug with the Russian client, and I have no clue why. I just tried resetting my WTF folder to try the "new user" experience and it worked just as I expected on my end.

**Comment by Nikslg** [comment]
I did try resetting the profile. That's what I did before sending screenshot.
As for light version, Originally I was looking for addon to add new buttons with extra conditions that not related to any of 12 hotbars because I am kinda tired of wasting full bar for PvP Icon...
But yes, It is Russian client bug, which is sad.

**Comment by Nikslg** [comment]
Edit: I found one bug in Bugsack. Your mod doesn't know how to react to russian value for "SetOrientation"

3x Neuron\Objects/STATUSBTN.lua:1730: NeuronStatusBar1_StatusBar1SB:SetOrientation(): Unknown orientation: ГОРИЗОНТАЛЬНЫЙ

**Comment by brittyazel** [comment]
hrm..ok. I'll try to fix that. I must have a bug in there that doesn't abstract out the translations. Give me a little bit and I'll get a new version out, thanks for finding the bug!

**Comment by brittyazel** [comment]
Ok I fixed that issue (and fixed a totally separate bug that I saw while I was at it). Please test with 1.0.7d and let me know if after refreshing your profile it still fails to load properly

**Comment by Nikslg** [comment]
New version actually shows most of the interface and works better, thank you.
I am able to see Casting panel and other things.
There is a minor inconvenient about "edit" text on the hotkeys.
In Russian interface "edit" transforms into "редактировать", which is quite long. Is it possible to keep it as "Edit" or  as "Изменить"?

**Comment by brittyazel** [comment]
Great! I'm happy that bug is fixed, you had me concerned.

About the translations, those are all handled by the community actually here:
https://wow.curseforge.com/projects/neuron/localization
With all the programming and development work, I don't have the capacity or bandwidth to handle all the localizations myself, so I'm leaning on you guys for that. If you see a translation that needs fixing, please feel free to make the changes yourself :-) . All the changes get packaged up in the following release
