### ISSUE TITLE
Macro/spell icons

### ISSUE THREAD

**Issue by Addonman** [brittyazel/Neuron#27]
I noticed some spells dont have icons when i put them on bar.For instance i try to pull 1st honor talent into bar i just get empty icon and text. i Even tried opening edit button and put icon from there and save it nothing is happening.

**Comment by brittyazel** [comment]
Is it empty while in a pvp setting also? When not in pvp setting those abilities are not active, and by default Neuron  displays buttons/macros for non-available abilities as blank. (I really should find a more informative way of displaying that info). 

In general, pvp abilities are tricky to deal with as they don't register as available abilities until you go into the pvp zone. If you are in a bg though, you can drag the button to the bar and it will be retained permanently, with the caveat that the button may look empty when in non pvp settings

**Comment by Vadrigarr** [comment]
I also have a problem related to the icons but in my case it only refers to the "dynamic" icons of the macros. For example, in a macro that unifies all the Hearthstones in a single button only shows the "?" instead of the right icon. The first time I put this kind of macros shows the icon correctly but when I press any modifier it shows again the "?". It also happens if the macro is to equip different objects, it only shows the "main" object's icon but not the others. I've already tried a clean installation of Neuron without luck. As a track, in the old "Ion" addon this function worked correctly :S . My game's localization is esES.

**Comment by brittyazel** [comment]
Ok I'll check into it. Can you paste one of the macros you are using so I know what to look for?

**Comment by Addonman** [comment]
Didnt check for pvp setting since i dont pvp lately only pvp on world pvp quests but all my chars are on pvp server so all my zones should be pvp zones?
Also i remeber same thing happens on my destruction lock with that spell that depends on what pet is out-i think its Command demon

**Comment by Vadrigarr** [comment]
One of the macros i mention:
--------------------------------------------
#showtooltip 
/cast [nomod]The Innkeeper's Daughter; [mod:ctrl]Argent Crusader's Tabard; [mod:alt]Dalaran Hearthstone; [mod:shift]Garrison Hearthstone
--------------------------------------------

**Comment by brittyazel** [comment]
@Addonman Yeah I think both of those are the same issue. When you aren't in a specific PVP zone (bg/arena) you can't use the honor talent spells because they aren't even in your spellbook until you enter those zones. Thus you can't drag it onto a bar, because there's nothing to drag onto the bar yet :-/ Being on a PvP server doesn't change anything, as non PvP specific zones on a PvP server are still PvE zones (with the caveat that you can murder eachother).
This might be the same for the warlock pet thing (I don't have a warlock so I can't test it).

The solution (for now at least, until blizzard changes something) is to enter a bg/arena and then put the abilities on the bar. Since they are in your spellbook when you zone into one of those zones, Neuron knows about them and can build a macro for them. Once you leave, the icon will dissapear (because the ability is gone from your spellbook), but the macro itself will remain.

**Comment by brittyazel** [comment]
@Addonman Can you confirm that the issue and solution I posted work for you? I just want to make sure this isn't a different issue altogether

**Comment by Addonman** [comment]
for pvp it seems thats the case-i got on world pvp quest and when i was in zone flaged i could normally put out pvp spell and spell should up,when i left pvp zone icon was gone as well.
On lock and command demon- i tried playing with pet on /off as well  thinking its similar thing.First it  didnt worked and gave me this bug:
Date: 2018-01-06 23:09:14
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\Neuron\Neuron_Buttons.lua line 2290:
   Invalid spell ID in GameTooltip:SetSpellByID
Debug:
   [C]: SetSpellByID()
   Neuron\Neuron_Buttons.lua:2290: MACRO_SetSpellTooltip()
   Neuron\Neuron_Buttons.lua:2370: MACRO_SetTooltip()
   Neuron\Neuron_Buttons.lua:2412:
      Neuron\Neuron_Buttons.lua:2397
   [C]: ?
   [C]: ?
   [C]: ?
   [C]: ?
   [C]: ?
   [C]: ?
   [C]: ?
Locals:
(*temporary) = GameTooltip {
 0 = <userdata>
 SetQuestLogRewardSpell = <function> defined @Interface\AddOns\TradeSkillInfo\LibExtraTip.lua:402
 SetSpellBookItem = <function> defined @Interface\AddOns\TradeSkillInfo\LibExtraTip.lua:402
 default = 1
 Hide = <function> defined =[C]:-1
 SetExistingSocketGem = <function> defined =[C]:-1
 SetCurrencyToken = <function> defined @Interface\AddOns\Altoholic\Tooltip.lua:680
 SetShapeshift = <function> defined @Interface\AddOns\TradeSkillInfo\LibExtraTip.lua:402
 hasMoney = 1
 SetVoidDepositItem = <function> defined =[C]:-1
 SetVoidWithdrawalItem = <function> defined =[C]:-1
 SetQuestRewardSpell = <function> defined @Interface\AddOns\TradeSkillInfo\LibExtraTip.lua:402
 LibExtraTipRight = <table> {
 }
 comparing = false
 SetSocketGem = <function> defined =[C]:-1
 SetHyperlink = <function> defined =[C]:-1
 Show = <function> defined @Interface\AddOns\TipTac\core.lua:920
 SetGuildBankItem = <function> defined =[C]:-1
 SetPetAction = <function> defined @Interface\AddOns\TradeSkillInfo\LibExtraTip.lua:402
 SetUnitDebuff = <function> defined =[C]:-1
 SetHeirloomByItemID = <function> defined =[C]:-1
 SetLootItem = <function> defined =[C]:-1
 SetQuestItem = <function> defined =[C]:-1
 SetVoidItem = <function> defined =[C]:-1
 SetTrainerService = <function> defined =[C]:-1
 numMoneyFrames = 1
 SetItemByID = <function> defined =[C]:-1
 FadeOut = <function> defined @Interface\AddOns\TipTac\core.lua:906
 SetInboxItem = <function> defined =[C]:-1
 SetBuybackItem = <function> defined =[C]:-1
 shoppingTooltips = <table> {
 }
 LibExtraTipLeft = <table> {
 }
 SetMerchantItem = <function> defined =[C]:-1
 SetQuestLogItem = <function> defined =[C]:-1
 SetRecipeReagentItem = <function> defined =[C]:-1
 SetUnitBuff = <function> defined =[C]:-1
 SetTalent = <function> defined @Interface\AddOns\TradeSkillInfo\LibExtraTip.lua:402
 SetTradePlayerItem = <function> defined =[C]:-1
 SetIconTextureAndText = <function> defined @Interface\AddOns\TipTacItemRef\core.lua:53
 SetSendMailItem = <function> defined =[C]:-1
 ttGradient = <unnamed> {
 }
 updateTooltip = 0.033999991416931
 SetInventoryItem = <function> defined =[C]:-1
 SetTradeTargetItem = <function> defined =[C]:-1
 ttCount = <unnamed> {
 }
 SetLootRollItem = <function> defined =[C]:-1
 SetUnitAura = <function> defined =[C]:-1
 ttIcon = <unnamed> {
 }
 CIMI_tooltipWritten = false
 SetBagItem = <function> defined =[C]:-1
 needsReset = true
 __tamedCounts = false
 SetAuctionSellItem = <function> defined =[C]:-1
 SetAuctionItem = <function> defined =[C]:-1
 SetRecipeResultItem = <function> defined =[C]:-1
}
(*temporary) = -1056946873

And as i was typing it i tried it again dismissing pet puting spell in bar and now it seems it works.I do remeber  that it worked for me in past in few instances but then it would get srewed again and didnt work .At least i now know what is causing all of this so i can play with it(dismising pets ,... ) to get it working again.

**Comment by brittyazel** [comment]
I can't do much to fix this issue unfortunately. This is on Blizzards end to fix
