### ISSUE TITLE
Icon fade with lack of power/expected range.

### ISSUE THREAD

**Issue by bolte-io** [brittyazel/Neuron#317]
Unsure if this one is just me...

With say Domino for example, if I am out of range, or if I do not have enough power to use a spell the icon fades. Also when pressing the cool down cycles through as a fade on the icon clockwise.

This does not seem to happen with Neuron enabled, it just stays faded, regardless of power level or range. Clicking will cause the spell to fire off, but will also not react when pressed. Example of the cooldown recharge working below. Neuron doesn't appear to display this at all.

![image](https://user-images.githubusercontent.com/51535687/65539352-29289e80-df01-11e9-9197-862ea11c9da0.png)

Is this just a missing feature or a bug?

**Comment by brittyazel** [comment]
This is not the behavior I experience. When I am out of range the abilities take on a red tint (by default) and if you don't have enough power (mana, rage, etc) the abilities will fade. 

I'm not sure exactly what the issue is with how you explained it. See the attached screenshots. The first shows the out of range red tint, the second shows the low mana spell icon fade

![WoWScrnShot_092419_115055](https://user-images.githubusercontent.com/3747347/65541207-b6e49980-dec1-11e9-918d-8f74e19ae112.jpg)
![WoWScrnShot_092419_115120](https://user-images.githubusercontent.com/3747347/65541211-b815c680-dec1-11e9-9912-98467d231fed.jpg)

**Comment by brittyazel** [comment]
make sure you have the "out of range" indicator toggled on in the bar settings for that bar btw.
