### ISSUE TITLE
Neuron Bars not showing on new characters.

### ISSUE THREAD

**Issue by TheOSC** [brittyazel/Neuron#365]
Since the 9.0,0 Launch running Neuron Version 1.4.0 whenever I make a new character I can not see nor interact with any of my action bars. Clicking the Minimap button will show the Vehicle and Region abilities but they can not be interacted with in any way. Here is a paste bin with various LUA errors that I receive when attempting to use Neuron.

https://pastebin.com/Z5xVVg2C

I am not totally sure why this happens as any characters which I logged into before the patch went live still have their correct bars and seem to work fine. Attempting to copy an existing profile to the new character does not fix the problem. Nor does activating a profile from an existing character.

The only way to have functional bars is to have a character that existed and was logged in with a neuron profile before the Shadowlands Pre-Patch.

**Comment by brittyazel** [comment]
Thanks for the bug report. I'll get on this asap

**Comment by TheOSC** [comment]
Thank you so much. Neuron is literally the only actionbar mod I can use these days. Thanks for the prompt reply and awesome work.

-Max
________________________________

**Comment by brittyazel** [comment]
Ugh, ok so this is a pain in the ass. So it turns out that when a new character is made, the value returned by the function GetSpecialization() is "5". I.e. The player isn't actually any particular spec, they're some intro-specific spec. Further, if I override the spec to be 1, which seems rational, you literally can't do anything because the game blocks you from accessing the spellbook to add any items to your bars.

So I don't know what to do. I can make the bug stop, but without access to the spellbook you cannot even begin to do even the first quest where you target the dummy and attack. So I need to create a custom state "5" I guess with the bar pre-populated with buttons. 

Mother forking shirt balls.

**Comment by TheOSC** [comment]
For what it's worth the error happens on allied race characters as well. I'm not sure if this is tied to the same issue or not since allied races start at level 10 and presumably wouldn't be stuck in this intro spec state.

Either way I really appreciate you looking into the error and being so transparent/communicative. Hopefully bliz hasn't made this too hard for you.

Keep up the excellent work!
-Max
________________________________

**Comment by brittyazel** [comment]
Heh Blizz definitely added some work to my plate, but it's all fine. I'm sure there's an elegant way to deal. For the time being (i.e. the next day or so) I'd recommend only enabling Neuron once a character is out of the tutorial zone and has a chosen spec. Then it should work just fine. I just need time to figure out how to do with this new, weird psuedo-spec/tutorial-state that they introduced

**Comment by brittyazel** [comment]
This is fixed now. New build coming out asap
