### ISSUE TITLE
Buttons aren't re-activating after CD expires

### ISSUE THREAD

**Issue by raysmith59** [brittyazel/Neuron#421]
Since 2 releases ago (May 11, I think), action buttons like Blizzard aren't lighting back up when the CD expires, they stay dark and apparently inactive but they can be used.  The more recent release doesn't fix the issue so I've reverted back to the version before May 11 and the issue has gone away again.

**Comment by brittyazel** [comment]
I can't replicated this. Which spells experience this? Mine all seem to be returning to normal just fine after the CD expires. I don't have a mage to test with; if you can give me a druid ability that replicates this then that'd be helpful.

The change you're referring to was on line 138 of BUTTON.lua. I removed "self:UpdateObjectVisibility()" because it was screwing up drag and drop. On the surface the change seems to do nothing, but that was apparently wrong. The issue is that I can't replicate it.

**Comment by raysmith59** [comment]
I wasn't able to find any druid abilities with the issue, most mage abilities are fine too except Blizzard and Frost Nova, both of those have the issue.  I can't think of anything that's special about those two, either... anything I can think of, other similar buttons are fine.  I'll check around on other toons to try for more examples.

**Comment by AlexFolland** [comment]
Is this happening after a bar state change while the abilities are on cooldown, animating bling, or something else like that?

**Comment by raysmith59** [comment]
I don't think those are factors.

I have noticed a couple of things:  1) When I disabled Cooldown Transparency the primary issue went away; 2) Doing that introduced another quirk that I probably just couldn't see before, those two abilities when the CD expires do NOT show the subtle light burst/sparkle on the button.  I'm not sure if that sparkle can be toggled so not sure what would cause it to fire or not fire.

**Comment by raysmith59** [comment]
Hunter Disengage exhibits the same behaviour.

**Comment by brittyazel** [comment]
In theory I fixed this.

**Comment by raysmith59** [comment]
Testing now, I'll try to have some feedback before the weekend.

**Comment by raysmith59** [comment]
I think it's good, I haven't noticed the issue lately.
