### ISSUE TITLE
Export/Import profile

### ISSUE THREAD

**Issue by nixxou** [brittyazel/Neuron#422]
Hi, i would very much like an export/import profile button. Serialize all data and show that in a windows where we can copy paste.
![unnamed](https://user-images.githubusercontent.com/45721836/118786087-c2a08300-b891-11eb-9e0b-ad24e0201c41.jpg)

**Comment by brittyazel** [comment]
Yep, I would as well. It's a work in progress. I have no ETA for this sorry.

**Comment by Sifuedition** [comment]
I'm having a weird issue. I play all classes. On my shaman, and only my shaman, it will frequently log me out of the game about 3 seconds after my UI loads. Sometimes, but not always, if I disable all addons and log into a character other than my shaman, I can then log out and log in on my shaman, it will stay logged in. Then, I can enable addons again. Next time I log out, I may or may not have to do it again. As you can imagine, this is highly annoying, especially since I am trialing with a new guild, and they asked me to play shaman.

I don't think this has anything to do with Neuron specifically, but, I think it may have something to do with a global LUA variable that is conflicting, or something. What I would like to do is start completely over with my addons. The problem with that, is I have a LOT of toons and a lot of addons. The last time I did something similar, I think it took 30+ hours to set up all of my addons. I am going through all of them and exporting profiles to try to speed this up as much as possible. Most of the last setup was Neuron and Grid2, because Grid was new to me. Grid has an export and it worked great for this "re-do".

This brought me to this post, and I'm sorry for the long story, but I guess now I know there isn't (yet) a way to export the profile without copying files from the current WTF/Addons folders. I'm worried about possible corruption within some of those files. The features in Neuron, especially for my druid, are a key reason I prefer Neuron, but, it also makes for a TON of time to set it up from scratch again, between all the forms/stances/conditions/states on all of the classes/specs I play plus all of the macros.

I have learned to save my profile as soon as I set up bars with the buttons, positions, binds, etc before dropping spells and macros on them so I can copy that template for each character, but, there is still the problem of sheer volume.
12 classes
36 specs
Druid has four specs with travel, flight, swimming, bear, cat, noform, stealth, and sometimes moonkin on 4 specs.
7*2 (balance/resto)
6*2 (guardian/feral)
That's 26 bar states to configure on one class. There's still the other 32 specs, lol.

Plus rogue has normal, stealth, shadowdance, vanish on 3 specs (9 bars) where I was doing something similar. This last time, I did my best to simply use one bar for all states, but, I can't reach enough keybinds to keep all stealth and non-stealth abilities on binds without separate bar setups. Since it is an alt kinda deep in my roster, I'm just living with not binding some I normally do so I can set up fewer bar states.

This feature is why I LOVE this addon so much and appreciate the work you do on it, but, MAN is it painful to set up from scratch.

**Comment by AlexFolland** [comment]
You could initialize your WTF folder as a git repository and commit to it each time you make a valuable addon configuration change.  That way, if anything messes up, you can reset to the latest commit.

The lower-tech way to do that is simply duplicating your WTF folder once in a while, which will let you use the files inside it whenever you need.

That being said, serializing the DB to a compressed string and printing that string is almost trivial.  It just needs a serializing library.  https://framagit.org/fperrad/lua-MessagePack looks like it might do the trick.  It's MIT-licensed, too; should be fine to use.

**Comment by brittyazel** [comment]
Ok I have implemented initial (preliminary) profile importing and exporting. Please, please, please test MASTER.

As a side note, I had to implement not only serialization but also zlib compression to reduce the size of the strings. Ace3 edit boxes don't handle long strings well I guess, and long string can hang the game for multiple seconds. It is not very pleasant, and I can't figure out a way around it. So any help there is welcome.

So yeah, if the game hangs for 3-4 seconds, that's normal. Apologies, but I can't figure out why. It has to do with the Ace3 GUI edit box being poorly optimized for lots of text.
