### ISSUE TITLE
Keybind issues for alt/shift bar states

### ISSUE THREAD

**Issue by sebastianulm** [brittyazel/Neuron#53]
I use a bar with Alt and Shift states. When I press either modifier, the bar toggles alright. As a test case, I bind one button with "e" the other one "f". Both binds work in "homestate", but not in "alt1" however, only one of them works when I press alt. I deleted Neuron.lua (and the .bak) and redid this. 
This does not fix the issue. 

If I pick a different Button, it works. Some Button Indexes seem to be buggy. 

As a work around I can bind the key, alt-thekey and shift-thekey. 

Let me know, if you need more info.

**Comment by brittyazel** [comment]
Ugh this is super weird. For me all my alt modifiers work fine, half my shift modifiers work, but non of my ctrl modifiers. How long has this been broken for can you remember? I wonder if it was recent or if this is long standing

**Comment by brittyazel** [comment]
Ok it turns out this isn't a Neuron issue at all. I look up and down the code, but it turns out that it was just default WoW keybinds being bound to those modifiers. I.E. Shift+1/2/3/4/5/6 are by default bound to page1-6, and ctrl+1-10 are by default bound to the pet bar.

To fix this just clear the keybinds in the keybind menu in the game, and then /reload. It should work then
