### ISSUE TITLE
Abilities with charges not displaying cooldown text

### ISSUE THREAD

**Issue by DivertedCircle** [brittyazel/Neuron#56]
I noticed this happening with my Enhancement Shaman's Rockbiter ability. If both charges of Rockbiter have been used and are recharging the button does not show cooldown text to indicate how much time is left until a charge regenerates.

**Comment by raysmith59** [comment]
I'm seeing the CD of the recharge in that scenario.  Assuming this hasn't been fixed in the meantime, I believe cooldown text can be disabled in two places, one in the main Interface section (Game -> ActionBars -> Show Numbers for Cooldowns) as well as in the Neuron config for the action bar (uncheck Cooldown Countdown near the bottom right)... the alpha setting for that second one may also have an impact if alpha works.  You'll want to check that all or some combination of those haven't been disabled.
