### ISSUE TITLE
Abilities not staying locked to action bar

### ISSUE THREAD

**Issue by Trajin** [brittyazel/Neuron#64]
I know that the latest version was supposed to fix this bug, but it happened to me this morning.  I dragged an ability to action bar 3 and then when I went to click on another button, the cursor was set to the little drag/hand icon.   resetting the UI fixed it.

**Comment by brittyazel** [comment]
Interesting, ok I'll keep on it. Thanks!

**Comment by brittyazel** [comment]
I can't seem to replicate this. No matter how many times I try dragging stuff around and from the spellbook it seems to always work. Can you give me an order of steps 1) 2) 3) etc., that you can use that always experiences this issue?

**Comment by Trajin** [comment]
I've seen this happen more when I drag a quest item to the action bar.   If that helps.  These low level toons don't get those missions as often as when I was grinding rep in Argus.

**Comment by Trajin** [comment]
I've just had this happen when dragging a mount to the action bar.   

On a side note, how do you reenable the breath/fatigue bar if you delete the status bars?

**Comment by brittyazel** [comment]
Create a new status bar, open up the 'button' editor, right click on the status bar you want to be a breath/fatigue bar and  set it to be of type "mirror bar"

**Comment by brittyazel** [comment]
Ok Just pushed a new minor release. This is my second attempt at a working cursor drag. Just a note, ability is 'sticky' to the cursor, and to clear the cursor you have to click somewhere other than a button. Unfortunately, this requires you to click somewhere in the world in-between dragging abilities from the spellbook if you are overwriting abilities, otherwise the previous buttons macro data is still cached. I don't know how to work around this issue, as to do so would mean I have to hack into a bunch of blizzard code.
